# -*- coding: utf-8 -*-
"""detect.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y2ss3Gdf0X9sYfEQxxJXBukv1T5qM5F6
"""

from ultralytics import YOLO
from PIL import Image
import numpy as np

# Load model sekali saja
model = YOLO("model/best.pt")

def detect_oil_spill(image: Image.Image):
    results = model.predict(image)
    result_img = results[0].plot()
    detected = len(results[0].boxes) > 0
    return Image.fromarray(result_img), detected